var allMoney = prompt('How much money do you have?')
var apples = prompt ('How many apples have you bought?')
var breads = prompt('How many breads have you bought?')
var oneApple = prompt('How much is one apple?')
var sumApples = parseInt(apples) * parseInt(oneApple)
var oneBread = prompt('How much is one bread?')
var sumBreads = parseInt(oneBread) * parseInt(breads)
var fullExpenses = parseInt( allMoney) >= (sumApples + sumBreads)
document.write(fullExpenses)
